### ISSUE TITLE
Common CSV parser

### ISSUE THREAD

**Issue by schr476** [JeffersonLab/jlab_datascience_core#24]
- [x] Migrate common CVS data parser to core framework.

**Comment by schr476** [comment]
@sgoldenCS what is the status on this?

**Comment by sgoldenCS** [comment]
@schr476 At the meeting yesterday, we thought the parser was complete as it is already pulled into the main branch with unit tests. Additionally, other people in our group have started to use it and we have found that it generally implements all of the functionality we currently need. I was planning on writing some comments here and closing the issue...

**Comment by sgoldenCS** [comment]
I've created a new module in a branch tied to this issue that implements a CSVParser. I've tested it using the pandas_parser unit test since the code is essentially identical. This should also resolve issue #33.

**Comment by Kishanrajput** [comment]
This includes closed issue: https://github.com/JeffersonLab/jlab_datascience_core/issues/33
