### ISSUE TITLE
Wiki page for data preparation

### ISSUE THREAD

**Issue by schr476** [JeffersonLab/jlab_datascience_core#27]
Document on one wiki:
- [x]  core data preparation
- [x]  any examples?

Use link:
https://github.com/JeffersonLab/jlab_datascience_core/wiki/Data-Preparation

Use example:
https://github.com/JeffersonLab/SciOptControlToolkit/wiki/Agents

**Comment by ahmedmohammed107** [comment]
@sgoldenCS @dlersch @Kishanrajput @schr476
Please let me know what you think about the structure of the of the data prep module I wrote in the wiki page.

**Comment by Kishanrajput** [comment]
Could you please provide two things:
1. Input suggestions for different functions described
2. An example that you may know of such implementation (not important)

**Comment by Kishanrajput** [comment]
Please also include suggested config input to the module, see issue #25 for reference.
