### ISSUE TITLE
Data Parser for halls - documentation

### ISSUE THREAD

**Issue by Kishanrajput** [JeffersonLab/jlab_datascience_core#3]

**Comment by sgoldenCS** [comment]
I've begun trying to gather scripts that Torri Jeske and Adam Carpenter use to get data from the Halls and CEBAF. Hopefully having some examples of what people are already doing will allow us to fit their current solutions into our framework/workflow.

After speaking with Torri last week, I think it would be really useful for the Halls if we had a module that could read different process variables (PVs) or experimental data from the different databases (CCDB, EPICS, etc) and output that data in some nice format. 

It would then be trivial to build evaluation modules to visualize the input data (e.g. correlation plots, detector visualizations) and provide statistics. Even without ML models, this could help with getting buy in from the halls, especially if these modules are very simple to use (or we can provide a simple front-end) and more efficient than their current hacked together solutions.
