### ISSUE TITLE
Change PandasParser to CSVParser

### ISSUE THREAD

**Issue by schr476** [JeffersonLab/jlab_datascience_core#33]
The input file type should define the name of the data parser.

**Comment by sgoldenCS** [comment]
I've removed the bug label as I think it's inappropriate here. Everything works as intended. 

If you want a parser that only handles CSV files, there are many possible solutions to migrate the current code. I will implement one and we can discuss.

**Comment by schr476** [comment]
@sgoldenCS , the goal of the parser is to read in the data.
Please change the Pandas Parser to CSV parcer.
1) input: CSV
2) output: Pandas

**Comment by schr476** [comment]
@sgoldenCS , I was trying to focus on the fact that the parser is reading a data type and the naming convention should be based on the input not the output.

**Comment by Kishanrajput** [comment]
This has been done with issue: https://github.com/JeffersonLab/jlab_datascience_core/issues/24
