### ISSUE TITLE
Implement Hydra for cfg management

### ISSUE THREAD

**Issue by dlersch** [JeffersonLab/jlab_datascience_core#46]
Please implement [Pythons Hydra](https://hydra.cc/docs/intro/) for configuration management. Here are a few key points to consider:
- How to handle multiple configurations for the same module ?
- Are predefined configuration classes (I think they are called data sets?) helpful ?
- Is there a "good" way to define a folder structure for the configurations, i.e. a non confusing one

When working on this issue, please follow the procedure:
- [ ] Issue
- [ ] Branch
- [ ] Software
- [ ] Unit-Test
- [ ] Pull request

Please document all your work in this issue. I appreciate any private conversation or small chat in the office. However, for the sake of transparency, we should document all our work here.

**Comment by sgoldenCS** [comment]
The branch in this issue now includes a Hydra implementation of our example workflow. Only a few changes were needed to make this happen. I will make a pull request for these changes. I'm not sure if the pull request should close this issue or not, but it's a good start.
